In [1]:
import numpy as np
A = np.matrix([[1,2,4],[2,3,8],[-1,-3,-1]])
Q, R = np.linalg.qr(A)

In [2]:
def qr_iteration(A, iter):
    n = A.shape[0]
    U = np.eye(n)
    for i in range(iter):
        Q, R = np.linalg.qr(A)
        A = R @ Q
        U = U @ Q 
    return A, U

In [3]:
B = np.matrix([[2, -1], [-1, 4]])
B

matrix([[ 2, -1],
        [-1,  4]])

In [4]:
B_diagonal, U = qr_iteration(B, 1000)
U @ B_diagonal @ U.transpose()

matrix([[ 2., -1.],
        [-1.,  4.]])

In [5]:
B_diagonal

matrix([[ 4.41421356e+00, -4.86976762e-16],
        [ 0.00000000e+00,  1.58578644e+00]])

In [6]:
np.linalg.eig(B)[0]

array([1.58578644, 4.41421356])